services:
  jellyfin:
    extends:
      file: ../../_base.yml
      service: common-base
    container_name: ${COMPOSE_PROJECT_NAME:-alwazw_swarm}_jellyfin
    image: lscr.io/linuxserver/jellyfin:latest
    ports:
      - "${JELLYFIN_PORT}:8096"
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      # TZ is inherited from _base.yml
    volumes:
      - jellyfin_config:/config
      - ${MEDIA_BASE_PATH}:/data
    networks:
      - media_network