services:
  plex:
    extends:
      file: ../../_base.yml
      service: common-base
    container_name: ${COMPOSE_PROJECT_NAME:-alwazw_swarm}_plex
    image: lscr.io/linuxserver/plex:latest
    ports:
      - "${PLEX_PORT}:32400"
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      # TZ is inherited from _base.yml
      VERSION: "docker"
      PLEX_CLAIM: "${PLEX_CLAIM}"
    volumes:
      - plex_config:/config
      - ${MEDIA_BASE_PATH}:/data
    networks:
      - media_network