# =============================================================================
# PLEX - Media Server
# =============================================================================

services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - VERSION=docker
      - PLEX_CLAIM= # Optional: Get from https://plex.tv/claim
    volumes:
      - plex_config:/config
      - ${MEDIA_TV_SERIES_PATH}:/tv
      - ${MEDIA_MOVIES_PATH}:/movies
      - ${MEDIA_MUSIC_PATH}:/music
      - ${MEDIA_PHOTOS_PATH}:/photos
    ports:
      - "32400:32400"
      - "1900:1900/udp"
      - "3005:3005"
      - "5353:5353/udp"
      - "8324:8324"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
      - "32469:32469"
    networks:
      - media_network
      - proxy_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plex.rule=Host(`${PLEX_SUBDOMAIN}.${PRIMARY_DOMAIN}`) || Host(`${PLEX_SUBDOMAIN}.${SECONDARY_DOMAIN}`)"
      - "traefik.http.routers.plex.tls=true"
      - "traefik.http.routers.plex.tls.certresolver=${CERT_RESOLVER}"
      - "traefik.http.services.plex.loadbalancer.server.port=32400"


# =============================================================================
# NETWORKS
# =============================================================================
networks:
  nextcloud_network:
    driver: bridge
    internal: false
  media_network:
    driver: bridge
    internal: false
  proxy_network:
    external: true

# =============================================================================
# VOLUMES
# =============================================================================
volumes:
  # Nextcloud
  nextcloud_data:
  nextcloud_db_data:
  
  # Syncthing
  syncthing_config:
  
  # Plex
  plex_config:
  
  # Jellyfin
  jellyfin_config:
  
  # PhotoPrism
  photoprism_storage:
  photoprism_db_data:
  
  # Immich
  immich_model_cache:
  immich_postgres_data:
  
  # FileBrowser
  filebrowser_config:
  filebrowser_database:
  
  # Duplicati
  duplicati_config:

##############################################################33

