version: '3.8'
services:
  nextcloud:
    image: nextcloud:latest
    container_name: ${COMPOSE_PROJECT_NAME:-alwazw_swarm}_nextcloud
    restart: unless-stopped
    environment:
      - MYSQL_HOST=mariadb
      - MYSQL_DATABASE=${NEXTCLOUD_DB_NAME:-nextcloud}
      - MYSQL_USER=${NEXTCLOUD_DB_USER:-nextcloud}
      - MYSQL_PASSWORD=${NEXTCLOUD_DB_PASSWORD}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER:-alwazw}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - NEXTCLOUD_TRUSTED_DOMAINS=${DOMAIN}
    ports:
      - "${NEXTCLOUD_PORT:-8000}:80"
    volumes:
      - nextcloud_data:/var/www/html
      - ${NEXTCLOUD_DATA_PATH:-/data/nextcloud}:/var/www/html/data
    networks:
      - nextcloud_network
      - database_network
    depends_on:
      - mariadb
volumes:
  nextcloud_data:
networks:
  nextcloud_network:
    external: true
  database_network:
    external: true
