# =============================================================================
# NEXTCLOUD - Primary Cloud Storage & Sync
# =============================================================================

services:
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    environment:
      - MYSQL_HOST=nextcloud-db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_SUBDOMAIN}.${PRIMARY_DOMAIN} ${NEXTCLOUD_SUBDOMAIN}.${SECONDARY_DOMAIN} ${HOST_IP}
      - OVERWRITEPROTOCOL=https
      - OVERWRITEHOST=${NEXTCLOUD_SUBDOMAIN}.${PRIMARY_DOMAIN}
      - OVERWRITECLIURL=https://${NEXTCLOUD_SUBDOMAIN}.${PRIMARY_DOMAIN}
      - APACHE_DISABLE_REWRITE_IP=1
      - TRUSTED_PROXIES=traefik
    volumes:
      - nextcloud_data:/var/www/html
      - ${NEXTCLOUD_DATA_PATH}:/var/www/html/data
      - ${MEDIA_PHOTOS_PATH}:/var/www/html/data/photos
      - ${MEDIA_DOCUMENTS_PATH}:/var/www/html/data/documents
      - ${MEDIA_VIDEOS_PATH}:/var/www/html/data/videos
      - ${MEDIA_MUSIC_PATH}:/var/www/html/data/music
      - ${MEDIA_BOOKS_PATH}:/var/www/html/data/books
    depends_on:
      - nextcloud-db
      - nextcloud-redis
    networks:
      - nextcloud_network
      - proxy_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`${NEXTCLOUD_SUBDOMAIN}.${PRIMARY_DOMAIN}`) || Host(`${NEXTCLOUD_SUBDOMAIN}.${SECONDARY_DOMAIN}`) || Host(`${HOST_IP}`) && PathPrefix(`/nextcloud`)"
      - "traefik.http.routers.nextcloud.tls=true"
      - "traefik.http.routers.nextcloud.tls.certresolver=${CERT_RESOLVER}"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
      - "traefik.http.routers.nextcloud.middlewares=nextcloud-headers"
      - "traefik.http.middlewares.nextcloud-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.nextcloud-headers.headers.customrequestheaders.X-Forwarded-Host=${NEXTCLOUD_SUBDOMAIN}.${PRIMARY_DOMAIN}"

  # Nextcloud Database
  nextcloud-db:
    image: mariadb:latest
    container_name: nextcloud-db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - nextcloud_db_data:/var/lib/mysql
    networks:
      - nextcloud_network
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed

  # Nextcloud Redis Cache
  nextcloud-redis:
    image: redis:alpine
    container_name: nextcloud-redis
    restart: unless-stopped
    networks:
      - nextcloud_network
    command: redis-server --requirepass ${REDIS_PASSWORD}

# =============================================================================
# NETWORKS
# =============================================================================
networks:
  nextcloud_network:
    driver: bridge
    internal: false
  media_network:
    driver: bridge
    internal: false
  proxy_network:
    external: true

# =============================================================================
# VOLUMES
# =============================================================================
volumes:
  # Nextcloud
  nextcloud_data:
  nextcloud_db_data:
  
  # Syncthing
  syncthing_config:
  
  # Plex
  plex_config:
  
  # Jellyfin
  jellyfin_config:
  
  # PhotoPrism
  photoprism_storage:
  photoprism_db_data:
  
  # Immich
  immich_model_cache:
  immich_postgres_data:
  
  # FileBrowser
  filebrowser_config:
  filebrowser_database:
  
  # Duplicati
  duplicati_config:

  ######################################

