services:
  nextcloud:
    extends:
      file: ../../_base.yml
      service: common-base
    container_name: ${COMPOSE_PROJECT_NAME:-alwazw_swarm}_nextcloud
    image: lscr.io/linuxserver/nextcloud:latest
    ports:
      - "${NEXTCLOUD_HTTPS_PORT}:443"
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      # TZ is inherited from _base.yml
      POSTGRES_HOST: "postgres"
      POSTGRES_DB: "${NEXTCLOUD_DB_NAME}"
      POSTGRES_USER: "${NEXTCLOUD_DB_USER}"
      POSTGRES_PASSWORD: "${NEXTCLOUD_DB_PASSWORD}"
    volumes:
      - nextcloud_data:/data
      - nextcloud_config:/config
      - ${MEDIA_BASE_PATH}:/media
    networks:
      - database_network
      - nextcloud_network
