# docker-compose.yml
version: '3.8'
name: full_stack

# Component Files to be Included 
include:
  - path: ./_base.yml # <--- ADD THIS LINE FIRST! This ensures the anchor is defined.
#  - path: ./stacks/database/postgres.yml
#  - path: ./stacks/database/redis.yml
  - path: ./stacks/database/mariadb.yml
  - path: ./stacks/database/pgadmin.yml
#  - path: ./stacks/analytics/grafana.yml

# This file acts as the orchestrator, merging all component files
# services:

# Secrets
secrets:
  # Secrets are defined here because they are referred to by included services.
  postgres_user:
    file: ./secrets/postgres_user.txt
  postgres_password:
    file: ./secrets/postgres_password.txt
#
  puid:
    file: ./secrets/puid.txt
  pgid:
    file: ./secrets/pgid.txt
  mysql_user:
    file: ./secrets/mysql_user.txt
  mysql_user_password:
    file: ./secrets/mysql_user_password.txt
  mysql_root_password:
    file: ./secrets/mysql_root_password.txt
#
  pgadmin_email:
    file: ./secrets/pgadmin_email.txt
  pgadmin_password:
    file: ./secrets/pgadmin_password.txt
#
  grafana_password:
    file: ./secrets/grafana_password.txt


# All networks should be defined in the main compose file
networks:
  database_network:
    name: ${COMPOSE_PROJECT_NAME:-full_stack}_database_network
    driver: bridge
  analytics_network:
    name: ${COMPOSE_PROJECT_NAME:-full_stack}_analytics_network
    driver: bridge
#  networking_network:
#    driver: bridge
#  dashboard_network:
#    driver: bridge
#  analytics_network:
#    driver: bridge
#  media_network:
#    driver: bridge
#  automation_network:
#    driver: bridge
#  security_network:
#    driver: bridge
#  wazuh_network:
#    driver: bridge

# All named volumes should be defined here
volumes:
  # Database Volumes
  postgres_data:
  redis_data:
  mysql_config:
  pgadmin_data:
  # Analytics Volumes
  grafana_config:
  grafana_data:
  grafana_plugins:
  # Networking Volumes
 # librespeed_config:
 # adguardhome_work:
 # adguardhome_conf:
  # Security Volumes
 # vaultwarden_data:
 # wazuh_manager_data:
 # wazuh_manager_certs:
 # wazuh_indexer_data:
 # wazuh_dashboard_data:
  # Dashboard Volumes
 # heimdall_config:
  # Media Volumes
 # plex_config:
  # Automation Volumes
 # n8n_data:
 # home_assistant_config:
