# docker-compose.yml
name: ${COMPOSE_PROJECT_NAME:-alwazw_swarm}

# Component Files to be Included
include:
  - path: ./stacks/database/mariadb.yml
  - path: ./stacks/database/pgadmin.yml
  - path: ./stacks/database/postgres.yml
  - path: ./stacks/database/redis.yml
  - path: ./stacks/analytics/grafana.yml
  - path: ./stacks/nextcloud/nextcloud.yml
  - path: ./stacks/networking/cloudflared.yml
  - path: ./stacks/dashboards/heimdall.yml
  - path: ./stacks/monitoring/uptime_kuma.yml
  - path: ./stacks/security/vaultwarden.yml

# Secrets are defined here because they are referred to by included services.
secrets:
  puid:
    file: ./secrets/puid.txt
  pgid:
    file: ./secrets/pgid.txt
  mysql_user:
    file: ./secrets/mysql_user.txt
  mysql_user_password:
    file: ./secrets/mysql_user_password.txt
  mysql_root_password:
    file: ./secrets/mysql_root_password.txt
  pgadmin_password:
    file: ./secrets/pgadmin_password.txt
  postgres_user:
    file: ./secrets/postgres_user.txt
  postgres_password:
    file: ./secrets/postgres_password.txt
  grafana_password:
    file: ./secrets/grafana_password.txt
  cloudflare_tunnel_token:
    file: ./secrets/cloudflare_tunnel_token.txt

# All networks should be defined in the main compose file
networks:
  database_network:
    name: ${COMPOSE_PROJECT_NAME:-alwazw_swarm}_database_network
    driver: bridge
  analytics_network:
    name: ${COMPOSE_PROJECT_NAME:-alwazw_swarm}_analytics_network
    driver: bridge
  nextcloud_network:
    name: ${COMPOSE_PROJECT_NAME:-alwazw_swarm}_nextcloud_network
    driver: bridge
  dashboard_network:
    name: ${COMPOSE_PROJECT_NAME:-alwazw_swarm}_dashboard_network
    driver: bridge
  monitoring_network:
    name: ${COMPOSE_PROJECT_NAME:-alwazw_swarm}_monitoring_network
    driver: bridge
  security_network:
    name: ${COMPOSE_PROJECT_NAME:-alwazw_swarm}_security_network
    driver: bridge

# All named volumes should be defined here
volumes:
  mysql_config:
    name: ${COMPOSE_PROJECT_NAME:-alwazw_swarm}_mysql_config
  pgadmin_data:
    name: ${COMPOSE_PROJECT_NAME:-alwazw_swarm}_pgadmin_data
  postgres_data:
    name: ${COMPOSE_PROJECT_NAME:-alwazw_swarm}_postgres_data
  redis_data:
    name: ${COMPOSE_PROJECT_NAME:-alwazw_swarm}_redis_data
  grafana_data:
    name: ${COMPOSE_PROJECT_NAME:-alwazw_swarm}_grafana_data
  nextcloud_data:
    name: ${COMPOSE_PROJECT_NAME:-alwazw_swarm}_nextcloud_data
  nextcloud_config:
    name: ${COMPOSE_PROJECT_NAME:-alwazw_swarm}_nextcloud_config
  heimdall_config:
    name: ${COMPOSE_PROJECT_NAME:-alwazw_swarm}_heimdall_config
  uptime_kuma_data:
    name: ${COMPOSE_PROJECT_NAME:-alwazw_swarm}_uptime_kuma_data
  vaultwarden_data:
    name: ${COMPOSE_PROJECT_NAME:-alwazw_swarm}_vaultwarden_data
