version: '3.8'

services:
  # Core Infrastructure
  traefik:
    image: traefik:v3.0
    container_name: ${COMPOSE_PROJECT_NAME:-alwazw_swarm}_traefik
    restart: unless-stopped
    network_mode: host
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik:/etc/traefik

  # Analytics & Monitoring
  grafana:
    image: grafana/grafana:latest
    container_name: ${COMPOSE_PROJECT_NAME:-alwazw_swarm}_grafana
    restart: unless-stopped
    network_mode: host
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_SERVER_HTTP_PORT=${GRAFANA_PORT}
    volumes:
      - grafana_data:/var/lib/grafana

  prometheus:
    image: prom/prometheus:latest
    container_name: ${COMPOSE_PROJECT_NAME:-alwazw_swarm}_prometheus
    restart: unless-stopped
    network_mode: host
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.listen-address=0.0.0.0:9090'
    volumes:
      - ./config/prometheus:/etc/prometheus
      - prometheus_data:/prometheus

  node_exporter:
    image: prom/node-exporter:latest
    container_name: ${COMPOSE_PROJECT_NAME:-alwazw_swarm}_node_exporter
    restart: unless-stopped
    network_mode: host
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: ${COMPOSE_PROJECT_NAME:-alwazw_swarm}_cadvisor
    restart: unless-stopped
    network_mode: host
    privileged: true
    devices:
      - /dev/kmsg:/dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /cgroup:/cgroup:ro

  uptime_kuma:
    image: louislam/uptime-kuma:latest
    container_name: ${COMPOSE_PROJECT_NAME:-alwazw_swarm}_uptime_kuma
    restart: unless-stopped
    network_mode: host
    volumes:
      - uptime_kuma_data:/app/data

  # Logging
  loki:
    image: grafana/loki:latest
    container_name: ${COMPOSE_PROJECT_NAME:-alwazw_swarm}_loki
    restart: unless-stopped
    network_mode: host
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./config/loki:/etc/loki
      - loki_data:/loki

  promtail:
    image: grafana/promtail:latest
    container_name: ${COMPOSE_PROJECT_NAME:-alwazw_swarm}_promtail
    restart: unless-stopped
    network_mode: host
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - ./config/promtail:/etc/promtail
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro

  # Security
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: ${COMPOSE_PROJECT_NAME:-alwazw_swarm}_vaultwarden
    restart: unless-stopped
    network_mode: host
    environment:
      - WEBSOCKET_ENABLED=true
      - ADMIN_TOKEN=${VAULTWARDEN_ADMIN_TOKEN}
      - ROCKET_PORT=80
    volumes:
      - vaultwarden_data:/data

  # Dashboards
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: ${COMPOSE_PROJECT_NAME:-alwazw_swarm}_heimdall
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - heimdall_config:/config

  # File Sharing
  nextcloud:
    image: nextcloud:latest
    container_name: ${COMPOSE_PROJECT_NAME:-alwazw_swarm}_nextcloud
    restart: unless-stopped
    network_mode: host
    environment:
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - APACHE_HTTP_PORT=${NEXTCLOUD_PORT}
    volumes:
      - nextcloud_data:/var/www/html
      - ${NEXTCLOUD_DATA_PATH}:/var/www/html/data

  # Media
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: ${COMPOSE_PROJECT_NAME:-alwazw_swarm}_jellyfin
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - jellyfin_config:/config
      - ${MEDIA_PATH_MOVIES}:/data/movies
      - ${MEDIA_PATH_TV}:/data/tvshows
    devices:
      - /dev/dri:/dev/dri

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: ${COMPOSE_PROJECT_NAME:-alwazw_swarm}_plex
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=docker
    volumes:
      - plex_config:/config
      - ${MEDIA_PATH_MOVIES}:/movies
      - ${MEDIA_PATH_TV}:/tv

  # Database
  postgres:
    image: postgres:15
    container_name: ${COMPOSE_PROJECT_NAME:-alwazw_swarm}_postgres
    restart: unless-stopped
    network_mode: host
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: ${COMPOSE_PROJECT_NAME:-alwazw_swarm}_redis
    restart: unless-stopped
    network_mode: host
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  # Utilities
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: ${COMPOSE_PROJECT_NAME:-alwazw_swarm}_filebrowser
    restart: unless-stopped
    network_mode: host
    environment:
      - FB_BASEURL=/filebrowser
    volumes:
      - filebrowser_data:/database
      - ${FILEBROWSER_ROOT_PATH}:/srv
    ports:
      - "8080:80"

  # Networking
  adguard:
    image: adguard/adguardhome:latest
    container_name: ${COMPOSE_PROJECT_NAME:-alwazw_swarm}_adguard
    restart: unless-stopped
    network_mode: host
    volumes:
      - adguard_work:/opt/adguardhome/work
      - adguard_conf:/opt/adguardhome/conf
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "3080:3000/tcp"

volumes:
  grafana_data:
  prometheus_data:
  uptime_kuma_data:
  loki_data:
  vaultwarden_data:
  heimdall_config:
  nextcloud_data:
  jellyfin_config:
  plex_config:
  postgres_data:
  redis_data:
  filebrowser_data:
  adguard_work:
  adguard_conf:

