services:
  vaultwarden:
    extends:
      file: ../../_base.yml
      service: common-base
    container_name: ${COMPOSE_PROJECT_NAME:-alwazw_swarm}_vaultwarden
    image: ghcr.io/dani-garcia/vaultwarden:latest
    ports:
      - "${VAULTWARDEN_PORT:-8083}:80"
    environment:
      - WEBSOCKET_ENABLED=true
      - SIGNUPS_ALLOWED=false
      - ADMIN_TOKEN=${VAULTWARDEN_ADMIN_TOKEN}
    volumes:
      - vaultwarden_data:/data
    networks:
      - security_network
