services:
  vaultwarden:
    <<: *default-app-config # Extend common settings
    container_name: vaultwarden
    image: ghcr.io/dani-garcia/vaultwarden:latest
    restart: always
    ports:
      - "${VAULTWARDEN_PORT}:80"
    environment:
      - WEBSOCKET_ENABLED=true
      - SIGNUPS_ALLOWED=false # Set to true initially, then false
    volumes:
      - vaultwarden_data:/data # Changed to named volume
    networks:
      - security_network

networks:
  security_network:
    external: true
  wazuh_network:
    external: true
