version: '3.8'
services:
  wazuh:
    image: wazuh/wazuh-manager:latest
    container_name: ${COMPOSE_PROJECT_NAME:-alwazw_swarm}_wazuh
    restart: unless-stopped
    environment:
      - WAZUH_MANAGER_ADMIN_USER=${WAZUH_USER:-alwazw}
      - WAZUH_MANAGER_ADMIN_PASSWORD=${WAZUH_PASSWORD}
    ports:
      - "${WAZUH_PORT:-1514}:1514"
      - "${WAZUH_API_PORT:-55000}:55000"
    volumes:
      - wazuh_data:/var/ossec/data
      - wazuh_logs:/var/ossec/logs
    networks:
      - security_network
volumes:
  wazuh_data:
  wazuh_logs:
networks:
  security_network:
    external: true
