services:
  duplicati:
    extends:
      file: ../../_base.yml
      service: common-base
    container_name: ${COMPOSE_PROJECT_NAME:-alwazw_swarm}_duplicati
    image: lscr.io/linuxserver/duplicati:latest
    ports:
      - "${DUPLICATI_PORT}:8200"
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      # TZ is inherited from _base.yml
    volumes:
      - duplicati_config:/config
      - ${MEDIA_BASE_PATH}/backups:/backups # A place to store backups
      - /var/lib/docker/volumes:/source # Granting access to docker volumes for backup
    networks:
      - backup_network