version: '3.8'

services:
  rclone:
    image: rclone/rclone:latest
    container_name: ${COMPOSE_PROJECT_NAME:-alwazw_swarm}_rclone
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - "${RCLONE_PORT:-5572}:5572"
    volumes:
      - rclone_config:/config/rclone
      - rclone_data:/data
      - ${RCLONE_SOURCE_PATH:-/source}:/source
    networks:
      - backup_network
    command: rcd --rc-web-gui --rc-addr=0.0.0.0:5572 --rc-user=${RCLONE_USER:-alwazw} --rc-pass=${RCLONE_PASSWORD}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rclone.rule=Host(`rclone.${DOMAIN}`)"
      - "traefik.http.services.rclone.loadbalancer.server.port=5572"
      - "traefik.docker.network=traefik_network"

volumes:
  rclone_config:
  rclone_data:

networks:
  backup_network:
    external: true

