services:
  mariadb:
    extends:
      file: ../../_base.yml
      service: common-base
    container_name: ${COMPOSE_PROJECT_NAME:-alwazw_swarm}_mariadb
    image: lscr.io/linuxserver/mariadb:latest
    ports:
      - "${MYSQL_MAIN_PORT}:3306"
    environment:
      # TZ is inherited from _base.yml
      PUID_FILE: /run/secrets/puid
      PGID_FILE: /run/secrets/pgid
      MYSQL_DATABASE: ${MYSQL_MAIN_DATABASE}
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_USER_FILE: /run/secrets/mysql_user
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_user_password
    volumes:
      - mysql_config:/config
    networks:
      - database_network
    secrets:
      - puid
      - pgid
      - mysql_root_password
      - mysql_user
      - mysql_user_password
