services:
  mariadb:
    extends: # Use 'extends' to inherit configuration from another service definition
      service: x-common-service # Name of the service template in _base.yml
      file: ../../_base.yml    # Path to _base.yml relative to mariadb.yml    
#
    container_name: mysql_main
    image: lscr.io/linuxserver/mariadb:latest
#    restart: always
    ports:
      - "${MYSQL_MAIN_PORT}:3306"
    environment:
      PUID_FILE: /run/secrets/puid.txt
      PGID_FILE: /run/secrets/pgid.txt
      TZ: ${TZ}
      MYSQL_DATABASE: ${MYSQL_MAIN_DATABASE}
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_USER_FILE: /run/secrets/mysql_user
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_user_password
    volumes:
      - mysql_config:/config
    networks:
      - database_network
    secrets:
      - mysql_root_password
      - mysql_user
      - mysql_user_password
      - puid
      - pgid

volumes:
  mysql_config:

networks:
  database_network:
    external: true

#secrets:
#  puid:
#    file: ./secrets/puid.txt
#  pgid:
#    file: ./secrets/pgid.txt
#  mysql_user:
#    file: ./secrets/mysql_user.txt
#  mysql_user_password:
#    file: ./secrets/mysql_user_password.txt
#  mysql_root_password:
#    file: ./secrets/mysql_root_password.txt
