version: '3.8'
services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ${COMPOSE_PROJECT_NAME:-alwazw_swarm}_pgadmin
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
      - PGADMIN_LISTEN_PORT=80
    ports:
      - "${PGADMIN_PORT:-5433}:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - database_network
    depends_on:
      - postgres
volumes:
  pgadmin_data:
networks:
  database_network:
    external: true
