services:
  pgadmin:
    extends:
      file: ../../_base.yml
      service: common-base
    container_name: ${COMPOSE_PROJECT_NAME:-alwazw_swarm}_pgadmin
    image: dpage/pgadmin4:latest
    ports:
      - "${PGADMIN_PORT}:80"
    environment:
      # TZ is inherited from _base.yml
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/pgadmin_password
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_LISTEN_ADDRESS: "0.0.0.0"
      PGADMIN_LISTEN_PORT: "80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - database_network
    secrets:
      - pgadmin_password
