services:
  pgadmin:
    extends: # Use 'extends' to inherit configuration from another service definition
      service: x-common-service # Name of the service template in _base.yml
      file: ../../_base.yml    # Path to _base.yml relative to mariadb.yml    
#   
    container_name: pgadmin
    image: dpage/pgadmin4
#    restart: always
    ports:
      - "${PGADMIN_PORT}:80"
    environment:
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_DEFAULT_EMAIL_FILE: /run/secrets/pgadmin_email
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/pgadmin_password
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - database_network
    secrets:
      - pgadmin_email
      - pgadmin_password

volumes:
  pgadmin_data:

networks:
  database_network:
    external: true

#secrets:
#  pgadmin_email:
#    file: ./secrets/pgadmin_email.txt
#  pgadmin_password:
#    file: ./secrets/pgadmin_password.txt
