services:
  postgres:
    extends:
      file: ../../_base.yml
      service: common-base
    container_name: ${COMPOSE_PROJECT_NAME:-alwazw_swarm}_postgres
    image: postgres:16
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      # TZ is inherited from _base.yml
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: "${POSTGRES_MAIN_DB}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - database_network
    secrets:
      - postgres_user
      - postgres_password