#####################
# POSTGRES
#####################

services:
  postgres:
    image: postgres:latest
    container_name: postgres_main
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_MAIN_DB}
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - database_network
    secrets:
      - postgres_user
      - postgres_password

networks:
  database_network:
    external: true

secrets:
  postgres_user:
    file: ./secrets/postgres_user.txt
  postgres_password:
    file: ./secrets/postgres_password.txt
