version: '3.8'
services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: ${COMPOSE_PROJECT_NAME:-alwazw_swarm}_cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      - networking_network
networks:
  networking_network:
    external: true
