
# =============================================================================
# FILEBROWSER - Web File Manager
# =============================================================================

services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped
    environment:
      - FB_BASEURL=/files
    volumes:
      - ${MEDIA_BASE_PATH}:/srv
      - filebrowser_config:/config
      - filebrowser_database:/database
    networks:
      - media_network
      - proxy_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.filebrowser.rule=Host(`files.${PRIMARY_DOMAIN}`) || Host(`files.${SECONDARY_DOMAIN}`)"
      - "traefik.http.routers.filebrowser.tls=true"
      - "traefik.http.routers.filebrowser.tls.certresolver=${CERT_RESOLVER}"
      - "traefik.http.services.filebrowser.loadbalancer.server.port=80"


# =============================================================================
# NETWORKS
# =============================================================================
networks:
  nextcloud_network:
    driver: bridge
    internal: false
  media_network:
    driver: bridge
    internal: false
  proxy_network:
    external: true

# =============================================================================
# VOLUMES
# =============================================================================
volumes:
  # Nextcloud
  nextcloud_data:
  nextcloud_db_data:
  
  # Syncthing
  syncthing_config:
  
  # Plex
  plex_config:
  
  # Jellyfin
  jellyfin_config:
  
  # PhotoPrism
  photoprism_storage:
  photoprism_db_data:
  
  # Immich
  immich_model_cache:
  immich_postgres_data:
  
  # FileBrowser
  filebrowser_config:
  filebrowser_database:
  
  # Duplicati
  duplicati_config:

##############################################################33

