version: '3.8'
services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: ${COMPOSE_PROJECT_NAME:-alwazw_swarm}_filebrowser
    restart: unless-stopped
    ports:
      - "${FILEBROWSER_PORT:-8080}:80"
    volumes:
      - filebrowser_data:/database
      - ${FILEBROWSER_ROOT:-/data}:/srv
    networks:
      - utility_network
volumes:
  filebrowser_data:
networks:
  utility_network:
    external: true
