version: '3.8'
services:
  immich:
    image: ghcr.io/immich-app/immich-server:release
    container_name: ${COMPOSE_PROJECT_NAME:-alwazw_swarm}_immich
    restart: unless-stopped
    environment:
      - DB_HOSTNAME=postgres
      - DB_USERNAME=${IMMICH_DB_USER:-immich}
      - DB_PASSWORD=${IMMICH_DB_PASSWORD}
      - DB_DATABASE_NAME=${IMMICH_DB_NAME:-immich}
      - REDIS_HOSTNAME=redis
    ports:
      - "${IMMICH_PORT:-8098}:3001"
    volumes:
      - immich_upload:/usr/src/app/upload
      - ${IMMICH_PHOTOS_PATH:-/data/photos}:/usr/src/app/upload/library:ro
    networks:
      - utility_network
      - database_network
    depends_on:
      - postgres
      - redis
volumes:
  immich_upload:
networks:
  utility_network:
    external: true
  database_network:
    external: true
