version: '3.8'
services:
  photoprism:
    image: photoprism/photoprism:latest
    container_name: ${COMPOSE_PROJECT_NAME:-alwazw_swarm}_photoprism
    restart: unless-stopped
    environment:
      - PHOTOPRISM_ADMIN_PASSWORD=${PHOTOPRISM_PASSWORD}
      - PHOTOPRISM_HTTP_PORT=2342
      - PHOTOPRISM_DATABASE_DRIVER=mysql
      - PHOTOPRISM_DATABASE_SERVER=mariadb:3306
      - PHOTOPRISM_DATABASE_NAME=${PHOTOPRISM_DB_NAME:-photoprism}
      - PHOTOPRISM_DATABASE_USER=${PHOTOPRISM_DB_USER:-photoprism}
      - PHOTOPRISM_DATABASE_PASSWORD=${PHOTOPRISM_DB_PASSWORD}
    ports:
      - "${PHOTOPRISM_PORT:-8097}:2342"
    volumes:
      - photoprism_storage:/photoprism/storage
      - ${PHOTOPRISM_PHOTOS_PATH:-/data/photos}:/photoprism/originals:ro
    networks:
      - utility_network
      - database_network
    depends_on:
      - mariadb
volumes:
  photoprism_storage:
networks:
  utility_network:
    external: true
  database_network:
    external: true
