version: '3.8'
services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: ${COMPOSE_PROJECT_NAME:-alwazw_swarm}_syncthing
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - "${SYNCTHING_PORT:-8384}:8384"
      - "${SYNCTHING_SYNC_PORT:-22000}:22000/tcp"
      - "${SYNCTHING_DISCOVERY_PORT:-21027}:21027/udp"
    volumes:
      - syncthing_config:/config
      - ${SYNCTHING_DATA_PATH:-/data/sync}:/data
    networks:
      - utility_network
volumes:
  syncthing_config:
networks:
  utility_network:
    external: true
