# =============================================================================
# FLUENT BIT - Alternative Log Processor
# =============================================================================

services:
  fluent-bit:
    image: fluent/fluent-bit:latest
    container_name: fluent-bit
    restart: unless-stopped
    volumes:
      - ./config/fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
      - ./config/fluent-bit/parsers.conf:/fluent-bit/etc/parsers.conf:ro
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    depends_on:
      - loki
    networks:
      - logging_network

# =============================================================================
# NETWORKS
# =============================================================================
networks:
  logging_network:
    driver: bridge
    internal: false
  proxy_network:
    external: true

# =============================================================================
# VOLUMES
# =============================================================================
volumes:
  loki_data:
  promtail_data:
  elasticsearch_data:
  filebeat_data:
  graylog_mongo_data:
  graylog_opensearch_data:
  graylog_data:

#############################################
