version: '3.8'
services:
  fluent_bit:
    image: fluent/fluent-bit:latest
    container_name: ${COMPOSE_PROJECT_NAME:-alwazw_swarm}_fluent_bit
    restart: unless-stopped
    ports:
      - "${FLUENT_BIT_PORT:-24224}:24224"
    volumes:
      - ./config/fluent-bit:/fluent-bit/etc
      - /var/log:/var/log:ro
    networks:
      - logging_network
networks:
  logging_network:
    external: true
