version: '3.8'
services:
  graylog:
    image: graylog/graylog:5.2
    container_name: ${COMPOSE_PROJECT_NAME:-alwazw_swarm}_graylog
    restart: unless-stopped
    environment:
      - GRAYLOG_PASSWORD_SECRET=${GRAYLOG_PASSWORD_SECRET}
      - GRAYLOG_ROOT_PASSWORD_SHA2=${GRAYLOG_ROOT_PASSWORD_SHA2}
      - GRAYLOG_HTTP_EXTERNAL_URI=http://localhost:9000/
      - GRAYLOG_ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - GRAYLOG_MONGODB_URI=mongodb://mongo:27017/graylog
    ports:
      - "${GRAYLOG_PORT:-9000}:9000"
      - "${GRAYLOG_SYSLOG_PORT:-1514}:1514/udp"
    networks:
      - logging_network
    depends_on:
      - elasticsearch
networks:
  logging_network:
    external: true
