version: '3.8'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: ${COMPOSE_PROJECT_NAME:-alwazw_swarm}_kibana
    restart: unless-stopped
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "${KIBANA_PORT:-5601}:5601"
    networks:
      - logging_network
    depends_on:
      - elasticsearch
networks:
  logging_network:
    external: true
