version: '3.8'
services:
  logrotate:
    image: linkyard/docker-logrotate:latest
    container_name: ${COMPOSE_PROJECT_NAME:-alwazw_swarm}_logrotate
    restart: unless-stopped
    environment:
      - LOGROTATE_INTERVAL=daily
      - LOGROTATE_COPIES=7
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:rw
      - /var/log:/var/log:rw
    networks:
      - logging_network
networks:
  logging_network:
    external: true
