version: '3.8'

services:
  promtail:
    extends:
      file: ../../_base.yml
      service: common-base
    container_name: ${COMPOSE_PROJECT_NAME:-alwazw_swarm}_promtail
    image: grafana/promtail:latest
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - ./config/promtail:/etc/promtail
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - HOSTNAME=${HOSTNAME}
    networks:
      - logging_network
    depends_on:
      - loki
    labels:
      - "traefik.enable=false"

networks:
  logging_network:
    name: ${COMPOSE_PROJECT_NAME:-alwazw_swarm}_logging_network
    external: true

