version: '3.8'
services:
  vector:
    image: timberio/vector:latest
    container_name: ${COMPOSE_PROJECT_NAME:-alwazw_swarm}_vector
    restart: unless-stopped
    ports:
      - "${VECTOR_PORT:-8686}:8686"
    volumes:
      - ./config/vector:/etc/vector
      - /var/log:/var/log:ro
    networks:
      - logging_network
networks:
  logging_network:
    external: true
