services:
  n8n:
    extends:
      file: ../../_base.yml
      service: common-base
    container_name: ${COMPOSE_PROJECT_NAME:-alwazw_swarm}_n8n
    image: lscr.io/linuxserver/n8n:latest
    ports:
      - "${N8N_PORT}:5678"
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      # TZ is inherited from _base.yml
      WEBHOOK_URL: "${N8N_WEBHOOK_URL}"
    volumes:
      - n8n_data:/config
    networks:
      - automation_network