version: '3.8'
services:
  docker_socket_proxy:
    image: tecnativa/docker-socket-proxy:latest
    container_name: ${COMPOSE_PROJECT_NAME:-alwazw_swarm}_docker_socket_proxy
    restart: unless-stopped
    environment:
      - CONTAINERS=1
      - SERVICES=1
      - SWARM=1
      - NODES=1
      - NETWORKS=1
      - TASKS=1
    ports:
      - "${DOCKER_SOCKET_PROXY_PORT:-2375}:2375"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - monitoring_network
networks:
  monitoring_network:
    external: true
