version: '3.8'

services:
  prometheus:
    extends:
      file: ../../_base.yml
      service: common-base
    container_name: ${COMPOSE_PROJECT_NAME:-alwazw_swarm}_prometheus
    image: prom/prometheus:latest
    ports:
      - "${PROMETHEUS_PORT}:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
    volumes:
      - prometheus_data:/prometheus
      - ./config/prometheus:/etc/prometheus
    networks:
      - monitoring_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.${PRIMARY_DOMAIN}`)"
      - "traefik.http.routers.prometheus.tls=true"
      - "traefik.http.routers.prometheus.tls.certresolver=letsencrypt"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"

volumes:
  prometheus_data:
    name: ${COMPOSE_PROJECT_NAME:-alwazw_swarm}_prometheus_data

networks:
  monitoring_network:
    name: ${COMPOSE_PROJECT_NAME:-alwazw_swarm}_monitoring_network
    external: true

